config/routes.rb
Rails.application.routes.draw do
  root "restaurants#index"
  resources :restaurants do
    resources :reservations
  end
  resources :users
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :day, presence: true
  validates :time, presence: true
  validates :partysize, presence: true
  belongs_to :restaurant
  belongs_to :user
  validate :can_make



  def can_make
    unless partysize == nil || time == nil
      unless restaurant.has_capacity?(partysize, day, time)
        errors.add(:base, "at max capacity for hour")
      end
    end
  end






end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reservations
  has_many :users, through: :reservations


  # def capacity(date, hour)
  #   - find reservations on date
  #   - reservations on hour
  # end

  def has_capacity?(partysize, day, time)

    capacity - day_current_occs(day, time) - partysize >= 0
  end
#
  # def current_occs
  #   reservations.sum { |res| res.partysize }
  # end

  def day_current_occs(day, time)
    reservations.where(day: day).where(time: time).sum { |res| res.partysize }
  end








end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :reservations
  has_many :restaurants, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

 helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = Reservation.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.restaurant_id = @restaurant.id
    @reservation.user_id = current_user.id

    if @reservation.save

      redirect_to restaurant_reservation_url(@restaurant, @reservation)
    else
      render 'new'
    end
  end


  def show
    @reservation = Reservation.find(params[:id])
    @restaurant = Restaurant.find(params[:restaurant_id])

  end
  private
    def reservation_params
      params.require(:reservation).permit(:partysize, :time, :day)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def create

  end

  def new

  end

  def edit

  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def destroy

  end






end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

def create
  user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:notice] = "Welcome"
        redirect_to root_url
      else
        render "new"
      end
    end

   def destroy
      session[:user_id] = nil
      flash.notice = "You've logged out"
      redirect_to root_url
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @reservations = User.find_by(id: params[:id]).reservations
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new

    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.phone = params[:user][:phone]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash.notice %>
<section class="app_links_sec">
  <p class="app_links"><%= link_to "Restaurants", root_path %></p>
  <p class=“userinfo”>
    <% if current_user %>
      Signed in as <%= current_user.email %><br>
       <%= link_to "Log out", session_path("logout"), :method => :delete %><br>
       <%= link_to "My Reservations", user_path(session[:user_id]) %>
    <% else %>
      <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
    <% end %>
  </p>
</section>

<%= yield %>








</body>
</html>

app/views/reservations/new.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>

$( function() {
  $( "#reservation_day" ).datepicker({
    dateFormat: 'yy-mm-dd'
  });
} )
</script>



<%= form_for [@restaurant, @reservation] do |f| %>

  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reservation.errors.count, "error") %> prohibited
        this reservation from being saved:
      </h2>
      <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :day %>
  <%= f.text_field :day %>

  <%= f.label :time %>
  <%= f.text_field :time %>

  <%= f.label :partysize %>
  <%= f.text_field :partysize %>

  <%= f.submit "Reserve" %>

<% end %>

app/views/reservations/show.html.erb
<h1>Your Reservation Details are Below</h1>

<p>Date: <%=  @reservation.day  %> <br> </p>
<p>Time: <%=  @reservation.time %> <br> </p>
<p>Restaurant Name:  <%=  @reservation.restaurant.name %> <br> </p>



<%= image_tag "coupon.jpg" %>

app/views/restaurants/index.html.erb
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<link href="https://fonts.googleapis.com/css?family=Lobster+Two" rel="stylesheet">
<body>

<header>

  <h1>SeatYourself</h1>

</header>

<section ="about">
    <div class="inner_wrapper">
      <h4><b>Make Your Reservations</b></h4>
      <p>Navigate through a fantastic selections of your local city's most popular restaurants. Select a restaurant of your choice, and save time making reservations with the click of a button.</p>
    </div>
  </div>
</section>

<% @restaurants.each do |rest| %>
  <h1><%= link_to rest.name,
  restaurant_path(rest)%></h1>
 <h2><%= rest.address %></h2>
 <p><%= link_to "Restaurant Site", "http://"+rest.url, target: :_blank %></p><hr>
<% end %>


</body>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %> </h1>



<p> Address: <%= @restaurant.address %></p>
<p>Telephone:<%=@restaurant.tele %></p>
<p>Opens at: <%= @restaurant.opening_hour %></p>
<p>Closes at: <%= @restaurant.closing_hour %></p>
<p><%= link_to "Restaurant's Webpage", "http://"+@restaurant.url, target: :_blank %> </p>

<p><%= link_to("CREATE NEW RESERVATION", new_restaurant_reservation_path(@restaurant.id), :class => "new_resv") %></p><br>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1478015.5634402523!2d-80.44195165129489!3d43.65338719210714!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89d4cb90d7c63ba5%3A0x323555502ab4c477!2sToronto%2C+ON!5e0!3m2!1sen!2sca!4v1505348590283" width="600" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/users/new.html.erb
<h1>Create An Account</h1>

<%= form_for @user do |f| %>

<p><%= f.label :name %></p>
<p><%= f.text_field :name%></p>

<p><%= f.label :email %></p>
<p><%= f.text_field :email%></p>

<p><%= f.label :password %></p>
<p><%= f.password_field :password%></p>

<p><%= f.label :password_confirmation %></p>
<p><%= f.password_field :password_confirmation%></p>

<p><%= f.submit "Create a new user"%></p>

<% end %>

app/views/users/show.html.erb
<h1>Reservations</h1>

<% @reservations.each do |resv| %>

<p> Restaurant: <%= resv.restaurant.name %>  </p>
 <p> Date: <%= resv.day %> </p>
 <p> Group Size: <%= resv.partysize %> </P>
<p> Time: <%=resv.time %>:00 </p>
 <hr>
 <% end %>